### ISSUE TITLE
more sophisticated scoring

### ISSUE THREAD

**Issue by larsborn** [simpspector/simpspector#60]
if no one objects I would work on this 

... just to be clear: I will do it! No one else should create a pull request! No. One.

**Comment by tolry** [comment]
Ideas from today's coding dojo

* gadgets result object will get a new collection called 'stats'. A stat item consists of description, gadget reference, category, value und commit reference
* value is a number between 0..1, 0..100 (0..100 might be a good idea, because we should stick to ints in the database + a resolution of 1 percent should suffice when it comes to precision)
* category is an optional field
* some tools (e.g. phpmetrics) already compute an overall score by themselves, for other tools the gadgets will have to implement a logical calculation by themselves.

anything I missed? @simplethings/simpspector

**Comment by larsborn** [comment]
move to analyzer?

**Comment by DavidBadura** [comment]
No, the analyzer will not provide a score.

**Comment by tolry** [comment]
great discussion :wink:

**Comment by DavidBadura** [comment]
We had this discusion serval times :P

**Comment by tolry** [comment]
I know, therefore the emoticon :smile:

**Comment by tolry** [comment]
concept abandoned, we decided to improve details on badges instead

![](http://darkturkey.com/wp-content/uploads/2015/04/pivot.gif)
